/**
 * 约搭活动时区城市库（独立数据文件，按需被 meetup-timezone 引入）。
 * 覆盖各国首都、主要省会/州府与经济中心；中英名 + 常用别名，供本地优先搜索。
 * 由 scripts/_gen_meetup_tz_cities.py 生成，勿手改巨型列表时可重跑脚本。
 */

import type { MeetupTzCity } from "@andyyyds/meetup/lib/meetup-timezone-types";

export const MEETUP_TZ_CITIES_DATA: MeetupTzCity[] = [
  { id: "beijing", labelZh: "北京", labelEn: "Beijing", timeZone: "Asia/Shanghai", countryZh: "中国", aliases: ["Peking"] },
  { id: "shanghai", labelZh: "上海", labelEn: "Shanghai", timeZone: "Asia/Shanghai", countryZh: "中国" },
  { id: "tianjin", labelZh: "天津", labelEn: "Tianjin", timeZone: "Asia/Shanghai", countryZh: "中国" },
  { id: "chongqing", labelZh: "重庆", labelEn: "Chongqing", timeZone: "Asia/Shanghai", countryZh: "中国" },
  { id: "guangzhou", labelZh: "广州", labelEn: "Guangzhou", timeZone: "Asia/Shanghai", countryZh: "中国", aliases: ["Canton"] },
  { id: "shenzhen", labelZh: "深圳", labelEn: "Shenzhen", timeZone: "Asia/Shanghai", countryZh: "中国" },
  { id: "chengdu", labelZh: "成都", labelEn: "Chengdu", timeZone: "Asia/Shanghai", countryZh: "中国" },
  { id: "hangzhou", labelZh: "杭州", labelEn: "Hangzhou", timeZone: "Asia/Shanghai", countryZh: "中国" },
  { id: "wuhan", labelZh: "武汉", labelEn: "Wuhan", timeZone: "Asia/Shanghai", countryZh: "中国" },
  { id: "xian", labelZh: "西安", labelEn: "Xi'an", timeZone: "Asia/Shanghai", countryZh: "中国", aliases: ["Xian", "西安市"] },
  { id: "nanjing", labelZh: "南京", labelEn: "Nanjing", timeZone: "Asia/Shanghai", countryZh: "中国" },
  { id: "suzhou", labelZh: "苏州", labelEn: "Suzhou", timeZone: "Asia/Shanghai", countryZh: "中国" },
  { id: "qingdao", labelZh: "青岛", labelEn: "Qingdao", timeZone: "Asia/Shanghai", countryZh: "中国", aliases: ["Tsingtao"] },
  { id: "dalian", labelZh: "大连", labelEn: "Dalian", timeZone: "Asia/Shanghai", countryZh: "中国" },
  { id: "ningbo", labelZh: "宁波", labelEn: "Ningbo", timeZone: "Asia/Shanghai", countryZh: "中国" },
  { id: "xiamen", labelZh: "厦门", labelEn: "Xiamen", timeZone: "Asia/Shanghai", countryZh: "中国", aliases: ["Amoy"] },
  { id: "fuzhou", labelZh: "福州", labelEn: "Fuzhou", timeZone: "Asia/Shanghai", countryZh: "中国" },
  { id: "jinan", labelZh: "济南", labelEn: "Jinan", timeZone: "Asia/Shanghai", countryZh: "中国" },
  { id: "zhengzhou", labelZh: "郑州", labelEn: "Zhengzhou", timeZone: "Asia/Shanghai", countryZh: "中国" },
  { id: "changsha", labelZh: "长沙", labelEn: "Changsha", timeZone: "Asia/Shanghai", countryZh: "中国" },
  { id: "hefei", labelZh: "合肥", labelEn: "Hefei", timeZone: "Asia/Shanghai", countryZh: "中国" },
  { id: "nanchang", labelZh: "南昌", labelEn: "Nanchang", timeZone: "Asia/Shanghai", countryZh: "中国" },
  { id: "fuyang", labelZh: "阜阳", labelEn: "Fuyang", timeZone: "Asia/Shanghai", countryZh: "中国" },
  { id: "shenyang", labelZh: "沈阳", labelEn: "Shenyang", timeZone: "Asia/Shanghai", countryZh: "中国", aliases: ["Mukden"] },
  { id: "changchun", labelZh: "长春", labelEn: "Changchun", timeZone: "Asia/Shanghai", countryZh: "中国" },
  { id: "harbin", labelZh: "哈尔滨", labelEn: "Harbin", timeZone: "Asia/Shanghai", countryZh: "中国", aliases: ["Haerbin"] },
  { id: "shijiazhuang", labelZh: "石家庄", labelEn: "Shijiazhuang", timeZone: "Asia/Shanghai", countryZh: "中国" },
  { id: "taiyuan", labelZh: "太原", labelEn: "Taiyuan", timeZone: "Asia/Shanghai", countryZh: "中国" },
  { id: "hohhot", labelZh: "呼和浩特", labelEn: "Hohhot", timeZone: "Asia/Shanghai", countryZh: "中国", aliases: ["Huhehaote"] },
  { id: "nanning", labelZh: "南宁", labelEn: "Nanning", timeZone: "Asia/Shanghai", countryZh: "中国" },
  { id: "haikou", labelZh: "海口", labelEn: "Haikou", timeZone: "Asia/Shanghai", countryZh: "中国" },
  { id: "sanya", labelZh: "三亚", labelEn: "Sanya", timeZone: "Asia/Shanghai", countryZh: "中国" },
  { id: "guiyang", labelZh: "贵阳", labelEn: "Guiyang", timeZone: "Asia/Shanghai", countryZh: "中国" },
  { id: "kunming", labelZh: "昆明", labelEn: "Kunming", timeZone: "Asia/Shanghai", countryZh: "中国" },
  { id: "lhasa", labelZh: "拉萨", labelEn: "Lhasa", timeZone: "Asia/Shanghai", countryZh: "中国" },
  { id: "lanzhou", labelZh: "兰州", labelEn: "Lanzhou", timeZone: "Asia/Shanghai", countryZh: "中国" },
  { id: "xining", labelZh: "西宁", labelEn: "Xining", timeZone: "Asia/Shanghai", countryZh: "中国" },
  { id: "yinchuan", labelZh: "银川", labelEn: "Yinchuan", timeZone: "Asia/Shanghai", countryZh: "中国" },
  { id: "urumqi", labelZh: "乌鲁木齐", labelEn: "Urumqi", timeZone: "Asia/Urumqi", countryZh: "中国", aliases: ["Wulumuqi", "Ürümqi"] },
  { id: "hongkong", labelZh: "香港", labelEn: "Hong Kong", timeZone: "Asia/Hong_Kong", countryZh: "中国", aliases: ["HK", "Xianggang"] },
  { id: "macau", labelZh: "澳门", labelEn: "Macau", timeZone: "Asia/Macau", countryZh: "中国", aliases: ["Macao", "Aomen"] },
  { id: "taipei", labelZh: "台北", labelEn: "Taipei", timeZone: "Asia/Taipei", countryZh: "中国", aliases: ["Taibei"] },
  { id: "kaohsiung", labelZh: "高雄", labelEn: "Kaohsiung", timeZone: "Asia/Taipei", countryZh: "中国", aliases: ["Gaoxiong"] },
  { id: "taichung", labelZh: "台中", labelEn: "Taichung", timeZone: "Asia/Taipei", countryZh: "中国" },
  { id: "newyork", labelZh: "纽约", labelEn: "New York", timeZone: "America/New_York", countryZh: "美国", aliases: ["NYC", "New York City"] },
  { id: "losangeles", labelZh: "洛杉矶", labelEn: "Los Angeles", timeZone: "America/Los_Angeles", countryZh: "美国", aliases: ["LA", "L.A."] },
  { id: "chicago", labelZh: "芝加哥", labelEn: "Chicago", timeZone: "America/Chicago", countryZh: "美国" },
  { id: "houston", labelZh: "休斯顿", labelEn: "Houston", timeZone: "America/Chicago", countryZh: "美国" },
  { id: "phoenix", labelZh: "凤凰城", labelEn: "Phoenix", timeZone: "America/Phoenix", countryZh: "美国", aliases: ["菲尼克斯"] },
  { id: "philadelphia", labelZh: "费城", labelEn: "Philadelphia", timeZone: "America/New_York", countryZh: "美国", aliases: ["Philly"] },
  { id: "sanantonio", labelZh: "圣安东尼奥", labelEn: "San Antonio", timeZone: "America/Chicago", countryZh: "美国" },
  { id: "sandiego", labelZh: "圣地亚哥", labelEn: "San Diego", timeZone: "America/Los_Angeles", countryZh: "美国", aliases: ["圣迭戈"] },
  { id: "dallas", labelZh: "达拉斯", labelEn: "Dallas", timeZone: "America/Chicago", countryZh: "美国" },
  { id: "sanfrancisco", labelZh: "旧金山", labelEn: "San Francisco", timeZone: "America/Los_Angeles", countryZh: "美国", aliases: ["SF", "三藩市", "圣弗朗西斯科"] },
  { id: "austin", labelZh: "奥斯汀", labelEn: "Austin", timeZone: "America/Chicago", countryZh: "美国" },
  { id: "jacksonville", labelZh: "杰克逊维尔", labelEn: "Jacksonville", timeZone: "America/New_York", countryZh: "美国" },
  { id: "sanjose", labelZh: "圣何塞", labelEn: "San Jose", timeZone: "America/Los_Angeles", countryZh: "美国", aliases: ["圣荷西"] },
  { id: "fortworth", labelZh: "沃思堡", labelEn: "Fort Worth", timeZone: "America/Chicago", countryZh: "美国" },
  { id: "columbus", labelZh: "哥伦布", labelEn: "Columbus", timeZone: "America/New_York", countryZh: "美国" },
  { id: "charlotte", labelZh: "夏洛特", labelEn: "Charlotte", timeZone: "America/New_York", countryZh: "美国" },
  { id: "indianapolis", labelZh: "印第安纳波利斯", labelEn: "Indianapolis", timeZone: "America/Indiana/Indianapolis", countryZh: "美国", aliases: ["Indy"] },
  { id: "seattle", labelZh: "西雅图", labelEn: "Seattle", timeZone: "America/Los_Angeles", countryZh: "美国" },
  { id: "denver", labelZh: "丹佛", labelEn: "Denver", timeZone: "America/Denver", countryZh: "美国" },
  { id: "washington", labelZh: "华盛顿", labelEn: "Washington", timeZone: "America/New_York", countryZh: "美国", aliases: ["Washington DC", "DC", "华盛顿特区"] },
  { id: "boston", labelZh: "波士顿", labelEn: "Boston", timeZone: "America/New_York", countryZh: "美国" },
  { id: "elpaso", labelZh: "埃尔帕索", labelEn: "El Paso", timeZone: "America/Denver", countryZh: "美国" },
  { id: "detroit", labelZh: "底特律", labelEn: "Detroit", timeZone: "America/Detroit", countryZh: "美国" },
  { id: "nashville", labelZh: "纳什维尔", labelEn: "Nashville", timeZone: "America/Chicago", countryZh: "美国" },
  { id: "portland", labelZh: "波特兰", labelEn: "Portland", timeZone: "America/Los_Angeles", countryZh: "美国" },
  { id: "oklahomacity", labelZh: "俄克拉荷马城", labelEn: "Oklahoma City", timeZone: "America/Chicago", countryZh: "美国", aliases: ["OKC"] },
  { id: "lasvegas", labelZh: "拉斯维加斯", labelEn: "Las Vegas", timeZone: "America/Los_Angeles", countryZh: "美国", aliases: ["Vegas"] },
  { id: "memphis", labelZh: "孟菲斯", labelEn: "Memphis", timeZone: "America/Chicago", countryZh: "美国" },
  { id: "louisville", labelZh: "路易斯维尔", labelEn: "Louisville", timeZone: "America/Kentucky/Louisville", countryZh: "美国" },
  { id: "baltimore", labelZh: "巴尔的摩", labelEn: "Baltimore", timeZone: "America/New_York", countryZh: "美国" },
  { id: "milwaukee", labelZh: "密尔沃基", labelEn: "Milwaukee", timeZone: "America/Chicago", countryZh: "美国" },
  { id: "albuquerque", labelZh: "阿尔伯克基", labelEn: "Albuquerque", timeZone: "America/Denver", countryZh: "美国" },
  { id: "tucson", labelZh: "图森", labelEn: "Tucson", timeZone: "America/Phoenix", countryZh: "美国" },
  { id: "fresno", labelZh: "弗雷斯诺", labelEn: "Fresno", timeZone: "America/Los_Angeles", countryZh: "美国" },
  { id: "sacramento", labelZh: "萨克拉门托", labelEn: "Sacramento", timeZone: "America/Los_Angeles", countryZh: "美国" },
  { id: "mesa", labelZh: "梅萨", labelEn: "Mesa", timeZone: "America/Phoenix", countryZh: "美国" },
  { id: "kansascity", labelZh: "堪萨斯城", labelEn: "Kansas City", timeZone: "America/Chicago", countryZh: "美国" },
  { id: "atlanta", labelZh: "亚特兰大", labelEn: "Atlanta", timeZone: "America/New_York", countryZh: "美国" },
  { id: "miami", labelZh: "迈阿密", labelEn: "Miami", timeZone: "America/New_York", countryZh: "美国" },
  { id: "raleigh", labelZh: "罗利", labelEn: "Raleigh", timeZone: "America/New_York", countryZh: "美国" },
  { id: "omaha", labelZh: "奥马哈", labelEn: "Omaha", timeZone: "America/Chicago", countryZh: "美国" },
  { id: "minneapolis", labelZh: "明尼阿波利斯", labelEn: "Minneapolis", timeZone: "America/Chicago", countryZh: "美国" },
  { id: "cleveland", labelZh: "克利夫兰", labelEn: "Cleveland", timeZone: "America/New_York", countryZh: "美国" },
  { id: "tulsa", labelZh: "塔尔萨", labelEn: "Tulsa", timeZone: "America/Chicago", countryZh: "美国" },
  { id: "wichita", labelZh: "威奇托", labelEn: "Wichita", timeZone: "America/Chicago", countryZh: "美国" },
  { id: "neworleans", labelZh: "新奥尔良", labelEn: "New Orleans", timeZone: "America/Chicago", countryZh: "美国" },
  { id: "arlington", labelZh: "阿灵顿", labelEn: "Arlington", timeZone: "America/Chicago", countryZh: "美国" },
  { id: "tampa", labelZh: "坦帕", labelEn: "Tampa", timeZone: "America/New_York", countryZh: "美国" },
  { id: "honolulu", labelZh: "檀香山", labelEn: "Honolulu", timeZone: "Pacific/Honolulu", countryZh: "美国", aliases: ["火奴鲁鲁"] },
  { id: "anchorage", labelZh: "安克雷奇", labelEn: "Anchorage", timeZone: "America/Anchorage", countryZh: "美国" },
  { id: "saltlakecity", labelZh: "盐湖城", labelEn: "Salt Lake City", timeZone: "America/Denver", countryZh: "美国", aliases: ["SLC"] },
  { id: "boise", labelZh: "博伊西", labelEn: "Boise", timeZone: "America/Boise", countryZh: "美国" },
  { id: "richmond", labelZh: "里士满", labelEn: "Richmond", timeZone: "America/New_York", countryZh: "美国" },
  { id: "pittsburgh", labelZh: "匹兹堡", labelEn: "Pittsburgh", timeZone: "America/New_York", countryZh: "美国" },
  { id: "cincinnati", labelZh: "辛辛那提", labelEn: "Cincinnati", timeZone: "America/New_York", countryZh: "美国" },
  { id: "stlouis", labelZh: "圣路易斯", labelEn: "St. Louis", timeZone: "America/Chicago", countryZh: "美国", aliases: ["Saint Louis", "圣路易"] },
  { id: "orland", labelZh: "奥兰多", labelEn: "Orlando", timeZone: "America/New_York", countryZh: "美国" },
  { id: "buffalo", labelZh: "布法罗", labelEn: "Buffalo", timeZone: "America/New_York", countryZh: "美国", aliases: ["水牛城"] },
  { id: "rochester", labelZh: "罗切斯特", labelEn: "Rochester", timeZone: "America/New_York", countryZh: "美国" },
  { id: "providence", labelZh: "普罗维登斯", labelEn: "Providence", timeZone: "America/New_York", countryZh: "美国" },
  { id: "hartford", labelZh: "哈特福德", labelEn: "Hartford", timeZone: "America/New_York", countryZh: "美国" },
  { id: "albany", labelZh: "奥尔巴尼", labelEn: "Albany", timeZone: "America/New_York", countryZh: "美国" },
  { id: "madison", labelZh: "麦迪逊", labelEn: "Madison", timeZone: "America/Chicago", countryZh: "美国" },
  { id: "desmoines", labelZh: "得梅因", labelEn: "Des Moines", timeZone: "America/Chicago", countryZh: "美国" },
  { id: "littlerock", labelZh: "小石城", labelEn: "Little Rock", timeZone: "America/Chicago", countryZh: "美国" },
  { id: "jackson", labelZh: "杰克逊", labelEn: "Jackson", timeZone: "America/Chicago", countryZh: "美国" },
  { id: "birmingham", labelZh: "伯明翰", labelEn: "Birmingham", timeZone: "America/Chicago", countryZh: "美国" },
  { id: "montgomery", labelZh: "蒙哥马利", labelEn: "Montgomery", timeZone: "America/Chicago", countryZh: "美国" },
  { id: "batonrouge", labelZh: "巴吞鲁日", labelEn: "Baton Rouge", timeZone: "America/Chicago", countryZh: "美国" },
  { id: "lincoln", labelZh: "林肯", labelEn: "Lincoln", timeZone: "America/Chicago", countryZh: "美国" },
  { id: "topeka", labelZh: "托皮卡", labelEn: "Topeka", timeZone: "America/Chicago", countryZh: "美国" },
  { id: "siouxfalls", labelZh: "苏福尔斯", labelEn: "Sioux Falls", timeZone: "America/Chicago", countryZh: "美国" },
  { id: "fargo", labelZh: "法戈", labelEn: "Fargo", timeZone: "America/Chicago", countryZh: "美国" },
  { id: "billings", labelZh: "比林斯", labelEn: "Billings", timeZone: "America/Denver", countryZh: "美国" },
  { id: "cheyenne", labelZh: "夏延", labelEn: "Cheyenne", timeZone: "America/Denver", countryZh: "美国" },
  { id: "helena", labelZh: "海伦娜", labelEn: "Helena", timeZone: "America/Denver", countryZh: "美国" },
  { id: "santfe", labelZh: "圣菲", labelEn: "Santa Fe", timeZone: "America/Denver", countryZh: "美国", aliases: ["Santa Fe"] },
  { id: "reno", labelZh: "里诺", labelEn: "Reno", timeZone: "America/Los_Angeles", countryZh: "美国" },
  { id: "spokane", labelZh: "斯波坎", labelEn: "Spokane", timeZone: "America/Los_Angeles", countryZh: "美国" },
  { id: "eugene", labelZh: "尤金", labelEn: "Eugene", timeZone: "America/Los_Angeles", countryZh: "美国" },
  { id: "juneau", labelZh: "朱诺", labelEn: "Juneau", timeZone: "America/Juneau", countryZh: "美国" },
  { id: "toronto", labelZh: "多伦多", labelEn: "Toronto", timeZone: "America/Toronto", countryZh: "加拿大" },
  { id: "vancouver", labelZh: "温哥华", labelEn: "Vancouver", timeZone: "America/Vancouver", countryZh: "加拿大" },
  { id: "montreal", labelZh: "蒙特利尔", labelEn: "Montreal", timeZone: "America/Toronto", countryZh: "加拿大", aliases: ["Montréal"] },
  { id: "calgary", labelZh: "卡尔加里", labelEn: "Calgary", timeZone: "America/Edmonton", countryZh: "加拿大" },
  { id: "ottawa", labelZh: "渥太华", labelEn: "Ottawa", timeZone: "America/Toronto", countryZh: "加拿大" },
  { id: "edmonton", labelZh: "埃德蒙顿", labelEn: "Edmonton", timeZone: "America/Edmonton", countryZh: "加拿大" },
  { id: "winnipeg", labelZh: "温尼伯", labelEn: "Winnipeg", timeZone: "America/Winnipeg", countryZh: "加拿大" },
  { id: "quebeccity", labelZh: "魁北克市", labelEn: "Quebec City", timeZone: "America/Toronto", countryZh: "加拿大", aliases: ["Quebec"] },
  { id: "halifax", labelZh: "哈利法克斯", labelEn: "Halifax", timeZone: "America/Halifax", countryZh: "加拿大" },
  { id: "victoria", labelZh: "维多利亚", labelEn: "Victoria", timeZone: "America/Vancouver", countryZh: "加拿大" },
  { id: "mexicocity", labelZh: "墨西哥城", labelEn: "Mexico City", timeZone: "America/Mexico_City", countryZh: "墨西哥", aliases: ["Ciudad de Mexico"] },
  { id: "guadalajara", labelZh: "瓜达拉哈拉", labelEn: "Guadalajara", timeZone: "America/Mexico_City", countryZh: "墨西哥" },
  { id: "monterrey", labelZh: "蒙特雷", labelEn: "Monterrey", timeZone: "America/Monterrey", countryZh: "墨西哥" },
  { id: "cancun", labelZh: "坎昆", labelEn: "Cancun", timeZone: "America/Cancun", countryZh: "墨西哥", aliases: ["Cancún"] },
  { id: "saopaulo", labelZh: "圣保罗", labelEn: "Sao Paulo", timeZone: "America/Sao_Paulo", countryZh: "巴西", aliases: ["São Paulo"] },
  { id: "riodejaneiro", labelZh: "里约热内卢", labelEn: "Rio de Janeiro", timeZone: "America/Sao_Paulo", countryZh: "巴西", aliases: ["Rio"] },
  { id: "brasilia", labelZh: "巴西利亚", labelEn: "Brasilia", timeZone: "America/Sao_Paulo", countryZh: "巴西", aliases: ["Brasília"] },
  { id: "buenosaires", labelZh: "布宜诺斯艾利斯", labelEn: "Buenos Aires", timeZone: "America/Argentina/Buenos_Aires", countryZh: "阿根廷" },
  { id: "santiago", labelZh: "圣地亚哥", labelEn: "Santiago", timeZone: "America/Santiago", countryZh: "智利" },
  { id: "lima", labelZh: "利马", labelEn: "Lima", timeZone: "America/Lima", countryZh: "秘鲁" },
  { id: "bogota", labelZh: "波哥大", labelEn: "Bogota", timeZone: "America/Bogota", countryZh: "哥伦比亚", aliases: ["Bogotá"] },
  { id: "caracas", labelZh: "加拉加斯", labelEn: "Caracas", timeZone: "America/Caracas", countryZh: "委内瑞拉" },
  { id: "quito", labelZh: "基多", labelEn: "Quito", timeZone: "America/Guayaquil", countryZh: "厄瓜多尔" },
  { id: "montevideo", labelZh: "蒙得维的亚", labelEn: "Montevideo", timeZone: "America/Montevideo", countryZh: "乌拉圭" },
  { id: "asuncion", labelZh: "亚松森", labelEn: "Asuncion", timeZone: "America/Asuncion", countryZh: "巴拉圭", aliases: ["Asunción"] },
  { id: "lapaz", labelZh: "拉巴斯", labelEn: "La Paz", timeZone: "America/La_Paz", countryZh: "玻利维亚" },
  { id: "havana", labelZh: "哈瓦那", labelEn: "Havana", timeZone: "America/Havana", countryZh: "古巴" },
  { id: "sanjose_cr", labelZh: "圣何塞", labelEn: "San Jose", timeZone: "America/Costa_Rica", countryZh: "哥斯达黎加" },
  { id: "panamacity", labelZh: "巴拿马城", labelEn: "Panama City", timeZone: "America/Panama", countryZh: "巴拿马" },
  { id: "kingston", labelZh: "金斯敦", labelEn: "Kingston", timeZone: "America/Jamaica", countryZh: "牙买加" },
  { id: "portofspain", labelZh: "西班牙港", labelEn: "Port of Spain", timeZone: "America/Port_of_Spain", countryZh: "特立尼达和多巴哥" },
  { id: "london", labelZh: "伦敦", labelEn: "London", timeZone: "Europe/London", countryZh: "英国" },
  { id: "manchester", labelZh: "曼彻斯特", labelEn: "Manchester", timeZone: "Europe/London", countryZh: "英国" },
  { id: "birmingham_uk", labelZh: "伯明翰", labelEn: "Birmingham", timeZone: "Europe/London", countryZh: "英国" },
  { id: "edinburgh", labelZh: "爱丁堡", labelEn: "Edinburgh", timeZone: "Europe/London", countryZh: "英国" },
  { id: "dublin", labelZh: "都柏林", labelEn: "Dublin", timeZone: "Europe/Dublin", countryZh: "爱尔兰" },
  { id: "paris", labelZh: "巴黎", labelEn: "Paris", timeZone: "Europe/Paris", countryZh: "法国" },
  { id: "lyon", labelZh: "里昂", labelEn: "Lyon", timeZone: "Europe/Paris", countryZh: "法国" },
  { id: "marseille", labelZh: "马赛", labelEn: "Marseille", timeZone: "Europe/Paris", countryZh: "法国" },
  { id: "berlin", labelZh: "柏林", labelEn: "Berlin", timeZone: "Europe/Berlin", countryZh: "德国" },
  { id: "munich", labelZh: "慕尼黑", labelEn: "Munich", timeZone: "Europe/Berlin", countryZh: "德国", aliases: ["München", "Munchen"] },
  { id: "frankfurt", labelZh: "法兰克福", labelEn: "Frankfurt", timeZone: "Europe/Berlin", countryZh: "德国" },
  { id: "hamburg", labelZh: "汉堡", labelEn: "Hamburg", timeZone: "Europe/Berlin", countryZh: "德国" },
  { id: "amsterdam", labelZh: "阿姆斯特丹", labelEn: "Amsterdam", timeZone: "Europe/Amsterdam", countryZh: "荷兰" },
  { id: "rotterdam", labelZh: "鹿特丹", labelEn: "Rotterdam", timeZone: "Europe/Amsterdam", countryZh: "荷兰" },
  { id: "brussels", labelZh: "布鲁塞尔", labelEn: "Brussels", timeZone: "Europe/Brussels", countryZh: "比利时" },
  { id: "luxembourg", labelZh: "卢森堡", labelEn: "Luxembourg", timeZone: "Europe/Luxembourg", countryZh: "卢森堡" },
  { id: "zurich", labelZh: "苏黎世", labelEn: "Zurich", timeZone: "Europe/Zurich", countryZh: "瑞士", aliases: ["Zürich"] },
  { id: "geneva", labelZh: "日内瓦", labelEn: "Geneva", timeZone: "Europe/Zurich", countryZh: "瑞士" },
  { id: "vienna", labelZh: "维也纳", labelEn: "Vienna", timeZone: "Europe/Vienna", countryZh: "奥地利" },
  { id: "rome", labelZh: "罗马", labelEn: "Rome", timeZone: "Europe/Rome", countryZh: "意大利", aliases: ["Roma"] },
  { id: "milan", labelZh: "米兰", labelEn: "Milan", timeZone: "Europe/Rome", countryZh: "意大利", aliases: ["Milano"] },
  { id: "madrid", labelZh: "马德里", labelEn: "Madrid", timeZone: "Europe/Madrid", countryZh: "西班牙" },
  { id: "barcelona", labelZh: "巴塞罗那", labelEn: "Barcelona", timeZone: "Europe/Madrid", countryZh: "西班牙" },
  { id: "lisbon", labelZh: "里斯本", labelEn: "Lisbon", timeZone: "Europe/Lisbon", countryZh: "葡萄牙", aliases: ["Lisboa"] },
  { id: "athens", labelZh: "雅典", labelEn: "Athens", timeZone: "Europe/Athens", countryZh: "希腊" },
  { id: "stockholm", labelZh: "斯德哥尔摩", labelEn: "Stockholm", timeZone: "Europe/Stockholm", countryZh: "瑞典" },
  { id: "oslo", labelZh: "奥斯陆", labelEn: "Oslo", timeZone: "Europe/Oslo", countryZh: "挪威" },
  { id: "copenhagen", labelZh: "哥本哈根", labelEn: "Copenhagen", timeZone: "Europe/Copenhagen", countryZh: "丹麦" },
  { id: "helsinki", labelZh: "赫尔辛基", labelEn: "Helsinki", timeZone: "Europe/Helsinki", countryZh: "芬兰" },
  { id: "warsaw", labelZh: "华沙", labelEn: "Warsaw", timeZone: "Europe/Warsaw", countryZh: "波兰", aliases: ["Warszawa"] },
  { id: "prague", labelZh: "布拉格", labelEn: "Prague", timeZone: "Europe/Prague", countryZh: "捷克", aliases: ["Praha"] },
  { id: "budapest", labelZh: "布达佩斯", labelEn: "Budapest", timeZone: "Europe/Budapest", countryZh: "匈牙利" },
  { id: "bucharest", labelZh: "布加勒斯特", labelEn: "Bucharest", timeZone: "Europe/Bucharest", countryZh: "罗马尼亚" },
  { id: "sofia", labelZh: "索非亚", labelEn: "Sofia", timeZone: "Europe/Sofia", countryZh: "保加利亚" },
  { id: "belgrade", labelZh: "贝尔格莱德", labelEn: "Belgrade", timeZone: "Europe/Belgrade", countryZh: "塞尔维亚" },
  { id: "zagreb", labelZh: "萨格勒布", labelEn: "Zagreb", timeZone: "Europe/Zagreb", countryZh: "克罗地亚" },
  { id: "ljubljana", labelZh: "卢布尔雅那", labelEn: "Ljubljana", timeZone: "Europe/Ljubljana", countryZh: "斯洛文尼亚" },
  { id: "bratislava", labelZh: "布拉迪斯拉发", labelEn: "Bratislava", timeZone: "Europe/Bratislava", countryZh: "斯洛伐克" },
  { id: "vilnius", labelZh: "维尔纽斯", labelEn: "Vilnius", timeZone: "Europe/Vilnius", countryZh: "立陶宛" },
  { id: "riga", labelZh: "里加", labelEn: "Riga", timeZone: "Europe/Riga", countryZh: "拉脱维亚" },
  { id: "tallinn", labelZh: "塔林", labelEn: "Tallinn", timeZone: "Europe/Tallinn", countryZh: "爱沙尼亚" },
  { id: "moscow", labelZh: "莫斯科", labelEn: "Moscow", timeZone: "Europe/Moscow", countryZh: "俄罗斯" },
  { id: "saintpetersburg", labelZh: "圣彼得堡", labelEn: "Saint Petersburg", timeZone: "Europe/Moscow", countryZh: "俄罗斯", aliases: ["St Petersburg", "彼得堡"] },
  { id: "kyiv", labelZh: "基辅", labelEn: "Kyiv", timeZone: "Europe/Kyiv", countryZh: "乌克兰", aliases: ["Kiev", "Київ"] },
  { id: "minsk", labelZh: "明斯克", labelEn: "Minsk", timeZone: "Europe/Minsk", countryZh: "白俄罗斯" },
  { id: "istanbul", labelZh: "伊斯坦布尔", labelEn: "Istanbul", timeZone: "Europe/Istanbul", countryZh: "土耳其" },
  { id: "ankara", labelZh: "安卡拉", labelEn: "Ankara", timeZone: "Europe/Istanbul", countryZh: "土耳其" },
  { id: "reykjavik", labelZh: "雷克雅未克", labelEn: "Reykjavik", timeZone: "Atlantic/Reykjavik", countryZh: "冰岛" },
  { id: "valletta", labelZh: "瓦莱塔", labelEn: "Valletta", timeZone: "Europe/Malta", countryZh: "马耳他" },
  { id: "nicosia", labelZh: "尼科西亚", labelEn: "Nicosia", timeZone: "Asia/Nicosia", countryZh: "塞浦路斯" },
  { id: "tokyo", labelZh: "东京", labelEn: "Tokyo", timeZone: "Asia/Tokyo", countryZh: "日本" },
  { id: "osaka", labelZh: "大阪", labelEn: "Osaka", timeZone: "Asia/Tokyo", countryZh: "日本" },
  { id: "kyoto", labelZh: "京都", labelEn: "Kyoto", timeZone: "Asia/Tokyo", countryZh: "日本" },
  { id: "nagoya", labelZh: "名古屋", labelEn: "Nagoya", timeZone: "Asia/Tokyo", countryZh: "日本" },
  { id: "fukuoka", labelZh: "福冈", labelEn: "Fukuoka", timeZone: "Asia/Tokyo", countryZh: "日本" },
  { id: "sapporo", labelZh: "札幌", labelEn: "Sapporo", timeZone: "Asia/Tokyo", countryZh: "日本" },
  { id: "seoul", labelZh: "首尔", labelEn: "Seoul", timeZone: "Asia/Seoul", countryZh: "韩国", aliases: ["汉城"] },
  { id: "busan", labelZh: "釜山", labelEn: "Busan", timeZone: "Asia/Seoul", countryZh: "韩国", aliases: ["Pusan"] },
  { id: "singapore", labelZh: "新加坡", labelEn: "Singapore", timeZone: "Asia/Singapore", countryZh: "新加坡" },
  { id: "bangkok", labelZh: "曼谷", labelEn: "Bangkok", timeZone: "Asia/Bangkok", countryZh: "泰国" },
  { id: "chiangmai", labelZh: "清迈", labelEn: "Chiang Mai", timeZone: "Asia/Bangkok", countryZh: "泰国" },
  { id: "kualalumpur", labelZh: "吉隆坡", labelEn: "Kuala Lumpur", timeZone: "Asia/Kuala_Lumpur", countryZh: "马来西亚", aliases: ["KL"] },
  { id: "penang", labelZh: "槟城", labelEn: "Penang", timeZone: "Asia/Kuala_Lumpur", countryZh: "马来西亚", aliases: ["乔治市"] },
  { id: "jakarta", labelZh: "雅加达", labelEn: "Jakarta", timeZone: "Asia/Jakarta", countryZh: "印尼" },
  { id: "bali", labelZh: "巴厘岛", labelEn: "Bali", timeZone: "Asia/Makassar", countryZh: "印尼", aliases: ["Denpasar", "登巴萨"] },
  { id: "manila", labelZh: "马尼拉", labelEn: "Manila", timeZone: "Asia/Manila", countryZh: "菲律宾" },
  { id: "cebu", labelZh: "宿务", labelEn: "Cebu", timeZone: "Asia/Manila", countryZh: "菲律宾" },
  { id: "hanoi", labelZh: "河内", labelEn: "Hanoi", timeZone: "Asia/Bangkok", countryZh: "越南", aliases: ["Ha Noi"] },
  { id: "hochiminh", labelZh: "胡志明市", labelEn: "Ho Chi Minh City", timeZone: "Asia/Ho_Chi_Minh", countryZh: "越南", aliases: ["Saigon", "西贡"] },
  { id: "phnompenh", labelZh: "金边", labelEn: "Phnom Penh", timeZone: "Asia/Phnom_Penh", countryZh: "柬埔寨" },
  { id: "vientiane", labelZh: "万象", labelEn: "Vientiane", timeZone: "Asia/Vientiane", countryZh: "老挝" },
  { id: "yangon", labelZh: "仰光", labelEn: "Yangon", timeZone: "Asia/Yangon", countryZh: "缅甸", aliases: ["Rangoon"] },
  { id: "naypyidaw", labelZh: "内比都", labelEn: "Naypyidaw", timeZone: "Asia/Yangon", countryZh: "缅甸" },
  { id: "delhi", labelZh: "新德里", labelEn: "New Delhi", timeZone: "Asia/Kolkata", countryZh: "印度", aliases: ["Delhi", "德里"] },
  { id: "mumbai", labelZh: "孟买", labelEn: "Mumbai", timeZone: "Asia/Kolkata", countryZh: "印度", aliases: ["Bombay"] },
  { id: "bangalore", labelZh: "班加罗尔", labelEn: "Bangalore", timeZone: "Asia/Kolkata", countryZh: "印度", aliases: ["Bengaluru"] },
  { id: "hyderabad", labelZh: "海得拉巴", labelEn: "Hyderabad", timeZone: "Asia/Kolkata", countryZh: "印度" },
  { id: "chennai", labelZh: "金奈", labelEn: "Chennai", timeZone: "Asia/Kolkata", countryZh: "印度", aliases: ["Madras"] },
  { id: "kolkata", labelZh: "加尔各答", labelEn: "Kolkata", timeZone: "Asia/Kolkata", countryZh: "印度", aliases: ["Calcutta"] },
  { id: "islamabad", labelZh: "伊斯兰堡", labelEn: "Islamabad", timeZone: "Asia/Karachi", countryZh: "巴基斯坦" },
  { id: "karachi", labelZh: "卡拉奇", labelEn: "Karachi", timeZone: "Asia/Karachi", countryZh: "巴基斯坦" },
  { id: "lahore", labelZh: "拉合尔", labelEn: "Lahore", timeZone: "Asia/Karachi", countryZh: "巴基斯坦" },
  { id: "dhaka", labelZh: "达卡", labelEn: "Dhaka", timeZone: "Asia/Dhaka", countryZh: "孟加拉国" },
  { id: "colombo", labelZh: "科伦坡", labelEn: "Colombo", timeZone: "Asia/Colombo", countryZh: "斯里兰卡" },
  { id: "kathmandu", labelZh: "加德满都", labelEn: "Kathmandu", timeZone: "Asia/Kathmandu", countryZh: "尼泊尔" },
  { id: "thimphu", labelZh: "廷布", labelEn: "Thimphu", timeZone: "Asia/Thimphu", countryZh: "不丹" },
  { id: "ulaanbaatar", labelZh: "乌兰巴托", labelEn: "Ulaanbaatar", timeZone: "Asia/Ulaanbaatar", countryZh: "蒙古" },
  { id: "pyongyang", labelZh: "平壤", labelEn: "Pyongyang", timeZone: "Asia/Pyongyang", countryZh: "朝鲜" },
  { id: "sydney", labelZh: "悉尼", labelEn: "Sydney", timeZone: "Australia/Sydney", countryZh: "澳大利亚" },
  { id: "melbourne", labelZh: "墨尔本", labelEn: "Melbourne", timeZone: "Australia/Melbourne", countryZh: "澳大利亚" },
  { id: "brisbane", labelZh: "布里斯班", labelEn: "Brisbane", timeZone: "Australia/Brisbane", countryZh: "澳大利亚" },
  { id: "perth", labelZh: "珀斯", labelEn: "Perth", timeZone: "Australia/Perth", countryZh: "澳大利亚" },
  { id: "adelaide", labelZh: "阿德莱德", labelEn: "Adelaide", timeZone: "Australia/Adelaide", countryZh: "澳大利亚" },
  { id: "canberra", labelZh: "堪培拉", labelEn: "Canberra", timeZone: "Australia/Sydney", countryZh: "澳大利亚" },
  { id: "auckland", labelZh: "奥克兰", labelEn: "Auckland", timeZone: "Pacific/Auckland", countryZh: "新西兰" },
  { id: "wellington", labelZh: "惠灵顿", labelEn: "Wellington", timeZone: "Pacific/Auckland", countryZh: "新西兰" },
  { id: "fiji", labelZh: "苏瓦", labelEn: "Suva", timeZone: "Pacific/Fiji", countryZh: "斐济" },
  { id: "portmoresby", labelZh: "莫尔兹比港", labelEn: "Port Moresby", timeZone: "Pacific/Port_Moresby", countryZh: "巴布亚新几内亚" },
  { id: "dubai", labelZh: "迪拜", labelEn: "Dubai", timeZone: "Asia/Dubai", countryZh: "阿联酋" },
  { id: "abudhabi", labelZh: "阿布扎比", labelEn: "Abu Dhabi", timeZone: "Asia/Dubai", countryZh: "阿联酋" },
  { id: "doha", labelZh: "多哈", labelEn: "Doha", timeZone: "Asia/Qatar", countryZh: "卡塔尔" },
  { id: "riyadh", labelZh: "利雅得", labelEn: "Riyadh", timeZone: "Asia/Riyadh", countryZh: "沙特阿拉伯" },
  { id: "jeddah", labelZh: "吉达", labelEn: "Jeddah", timeZone: "Asia/Riyadh", countryZh: "沙特阿拉伯" },
  { id: "kuwaitcity", labelZh: "科威特城", labelEn: "Kuwait City", timeZone: "Asia/Kuwait", countryZh: "科威特" },
  { id: "manama", labelZh: "麦纳麦", labelEn: "Manama", timeZone: "Asia/Bahrain", countryZh: "巴林" },
  { id: "muscat", labelZh: "马斯喀特", labelEn: "Muscat", timeZone: "Asia/Muscat", countryZh: "阿曼" },
  { id: "tehran", labelZh: "德黑兰", labelEn: "Tehran", timeZone: "Asia/Tehran", countryZh: "伊朗" },
  { id: "baghdad", labelZh: "巴格达", labelEn: "Baghdad", timeZone: "Asia/Baghdad", countryZh: "伊拉克" },
  { id: "amman", labelZh: "安曼", labelEn: "Amman", timeZone: "Asia/Amman", countryZh: "约旦" },
  { id: "beirut", labelZh: "贝鲁特", labelEn: "Beirut", timeZone: "Asia/Beirut", countryZh: "黎巴嫩" },
  { id: "damascus", labelZh: "大马士革", labelEn: "Damascus", timeZone: "Asia/Damascus", countryZh: "叙利亚" },
  { id: "jerusalem", labelZh: "耶路撒冷", labelEn: "Jerusalem", timeZone: "Asia/Jerusalem", countryZh: "以色列" },
  { id: "telaviv", labelZh: "特拉维夫", labelEn: "Tel Aviv", timeZone: "Asia/Jerusalem", countryZh: "以色列" },
  { id: "tbilisi", labelZh: "第比利斯", labelEn: "Tbilisi", timeZone: "Asia/Tbilisi", countryZh: "格鲁吉亚" },
  { id: "yerevan", labelZh: "埃里温", labelEn: "Yerevan", timeZone: "Asia/Yerevan", countryZh: "亚美尼亚" },
  { id: "baku", labelZh: "巴库", labelEn: "Baku", timeZone: "Asia/Baku", countryZh: "阿塞拜疆" },
  { id: "tashkent", labelZh: "塔什干", labelEn: "Tashkent", timeZone: "Asia/Tashkent", countryZh: "乌兹别克斯坦" },
  { id: "almaty", labelZh: "阿拉木图", labelEn: "Almaty", timeZone: "Asia/Almaty", countryZh: "哈萨克斯坦" },
  { id: "astana", labelZh: "阿斯塔纳", labelEn: "Astana", timeZone: "Asia/Almaty", countryZh: "哈萨克斯坦", aliases: ["Nur-Sultan", "努尔苏丹"] },
  { id: "bishkek", labelZh: "比什凯克", labelEn: "Bishkek", timeZone: "Asia/Bishkek", countryZh: "吉尔吉斯斯坦" },
  { id: "dushanbe", labelZh: "杜尚别", labelEn: "Dushanbe", timeZone: "Asia/Dushanbe", countryZh: "塔吉克斯坦" },
  { id: "ashgabat", labelZh: "阿什哈巴德", labelEn: "Ashgabat", timeZone: "Asia/Ashgabat", countryZh: "土库曼斯坦" },
  { id: "cairo", labelZh: "开罗", labelEn: "Cairo", timeZone: "Africa/Cairo", countryZh: "埃及" },
  { id: "alexandria", labelZh: "亚历山大", labelEn: "Alexandria", timeZone: "Africa/Cairo", countryZh: "埃及" },
  { id: "johannesburg", labelZh: "约翰内斯堡", labelEn: "Johannesburg", timeZone: "Africa/Johannesburg", countryZh: "南非" },
  { id: "capetown", labelZh: "开普敦", labelEn: "Cape Town", timeZone: "Africa/Johannesburg", countryZh: "南非" },
  { id: "pretoria", labelZh: "比勒陀利亚", labelEn: "Pretoria", timeZone: "Africa/Johannesburg", countryZh: "南非" },
  { id: "lagos", labelZh: "拉各斯", labelEn: "Lagos", timeZone: "Africa/Lagos", countryZh: "尼日利亚" },
  { id: "abuja", labelZh: "阿布贾", labelEn: "Abuja", timeZone: "Africa/Lagos", countryZh: "尼日利亚" },
  { id: "nairobi", labelZh: "内罗毕", labelEn: "Nairobi", timeZone: "Africa/Nairobi", countryZh: "肯尼亚" },
  { id: "addisababa", labelZh: "亚的斯亚贝巴", labelEn: "Addis Ababa", timeZone: "Africa/Addis_Ababa", countryZh: "埃塞俄比亚" },
  { id: "casablanca", labelZh: "卡萨布兰卡", labelEn: "Casablanca", timeZone: "Africa/Casablanca", countryZh: "摩洛哥" },
  { id: "rabat", labelZh: "拉巴特", labelEn: "Rabat", timeZone: "Africa/Casablanca", countryZh: "摩洛哥" },
  { id: "algiers", labelZh: "阿尔及尔", labelEn: "Algiers", timeZone: "Africa/Algiers", countryZh: "阿尔及利亚" },
  { id: "tunis", labelZh: "突尼斯", labelEn: "Tunis", timeZone: "Africa/Tunis", countryZh: "突尼斯" },
  { id: "tripoli", labelZh: "的黎波里", labelEn: "Tripoli", timeZone: "Africa/Tripoli", countryZh: "利比亚" },
  { id: "accra", labelZh: "阿克拉", labelEn: "Accra", timeZone: "Africa/Accra", countryZh: "加纳" },
  { id: "dakar", labelZh: "达喀尔", labelEn: "Dakar", timeZone: "Africa/Dakar", countryZh: "塞内加尔" },
  { id: "abidjan", labelZh: "阿比让", labelEn: "Abidjan", timeZone: "Africa/Abidjan", countryZh: "科特迪瓦" },
  { id: "kampala", labelZh: "坎帕拉", labelEn: "Kampala", timeZone: "Africa/Kampala", countryZh: "乌干达" },
  { id: "dar", labelZh: "达累斯萨拉姆", labelEn: "Dar es Salaam", timeZone: "Africa/Dar_es_Salaam", countryZh: "坦桑尼亚" },
  { id: "dodoma", labelZh: "多多马", labelEn: "Dodoma", timeZone: "Africa/Dar_es_Salaam", countryZh: "坦桑尼亚" },
  { id: "lusaka", labelZh: "卢萨卡", labelEn: "Lusaka", timeZone: "Africa/Lusaka", countryZh: "赞比亚" },
  { id: "harare", labelZh: "哈拉雷", labelEn: "Harare", timeZone: "Africa/Harare", countryZh: "津巴布韦" },
  { id: "maputo", labelZh: "马普托", labelEn: "Maputo", timeZone: "Africa/Maputo", countryZh: "莫桑比克" },
  { id: "gaborone", labelZh: "哈博罗内", labelEn: "Gaborone", timeZone: "Africa/Gaborone", countryZh: "博茨瓦纳" },
  { id: "windhoek", labelZh: "温得和克", labelEn: "Windhoek", timeZone: "Africa/Windhoek", countryZh: "纳米比亚" },
  { id: "khartoum", labelZh: "喀土穆", labelEn: "Khartoum", timeZone: "Africa/Khartoum", countryZh: "苏丹" },
  { id: "kigali", labelZh: "基加利", labelEn: "Kigali", timeZone: "Africa/Kigali", countryZh: "卢旺达" },
  { id: "antananarivo", labelZh: "塔那那利佛", labelEn: "Antananarivo", timeZone: "Indian/Antananarivo", countryZh: "马达加斯加" },
  { id: "portlouis", labelZh: "路易港", labelEn: "Port Louis", timeZone: "Indian/Mauritius", countryZh: "毛里求斯" },
  { id: "tirana", labelZh: "地拉那", labelEn: "Tirana", timeZone: "Europe/Tirana", countryZh: "阿尔巴尼亚" },
  { id: "andorra", labelZh: "安道尔城", labelEn: "Andorra la Vella", timeZone: "Europe/Andorra", countryZh: "安道尔" },
  { id: "nassau", labelZh: "拿骚", labelEn: "Nassau", timeZone: "America/Nassau", countryZh: "巴哈马" },
  { id: "bridgetown", labelZh: "布里奇顿", labelEn: "Bridgetown", timeZone: "America/Barbados", countryZh: "巴巴多斯" },
  { id: "belmopan", labelZh: "贝尔莫潘", labelEn: "Belmopan", timeZone: "America/Belize", countryZh: "伯利兹" },
  { id: "porto_novo", labelZh: "波多诺伏", labelEn: "Porto-Novo", timeZone: "Africa/Porto-Novo", countryZh: "贝宁" },
  { id: "sarajevo", labelZh: "萨拉热窝", labelEn: "Sarajevo", timeZone: "Europe/Sarajevo", countryZh: "波黑" },
  { id: "bandarseribegawan", labelZh: "斯里巴加湾市", labelEn: "Bandar Seri Begawan", timeZone: "Asia/Brunei", countryZh: "文莱" },
  { id: "ouagadougou", labelZh: "瓦加杜古", labelEn: "Ouagadougou", timeZone: "Africa/Ouagadougou", countryZh: "布基纳法索" },
  { id: "bujumbura", labelZh: "布琼布拉", labelEn: "Bujumbura", timeZone: "Africa/Bujumbura", countryZh: "布隆迪" },
  { id: "praia", labelZh: "普拉亚", labelEn: "Praia", timeZone: "Atlantic/Cape_Verde", countryZh: "佛得角" },
  { id: "bangui", labelZh: "班吉", labelEn: "Bangui", timeZone: "Africa/Bangui", countryZh: "中非" },
  { id: "ndjamena", labelZh: "恩贾梅纳", labelEn: "N'Djamena", timeZone: "Africa/Ndjamena", countryZh: "乍得" },
  { id: "moroni", labelZh: "莫罗尼", labelEn: "Moroni", timeZone: "Indian/Comoro", countryZh: "科摩罗" },
  { id: "brazzaville", labelZh: "布拉柴维尔", labelEn: "Brazzaville", timeZone: "Africa/Brazzaville", countryZh: "刚果（布）" },
  { id: "kinshasa", labelZh: "金沙萨", labelEn: "Kinshasa", timeZone: "Africa/Kinshasa", countryZh: "刚果（金）" },
  { id: "yamoussoukro", labelZh: "亚穆苏克罗", labelEn: "Yamoussoukro", timeZone: "Africa/Abidjan", countryZh: "科特迪瓦" },
  { id: "djibouti", labelZh: "吉布提", labelEn: "Djibouti", timeZone: "Africa/Djibouti", countryZh: "吉布提" },
  { id: "roseau", labelZh: "罗索", labelEn: "Roseau", timeZone: "America/Dominica", countryZh: "多米尼克" },
  { id: "santodomingo", labelZh: "圣多明各", labelEn: "Santo Domingo", timeZone: "America/Santo_Domingo", countryZh: "多米尼加" },
  { id: "dili", labelZh: "帝力", labelEn: "Dili", timeZone: "Asia/Dili", countryZh: "东帝汶" },
  { id: "sanjose_sv", labelZh: "圣萨尔瓦多", labelEn: "San Salvador", timeZone: "America/El_Salvador", countryZh: "萨尔瓦多" },
  { id: "malabo", labelZh: "马拉博", labelEn: "Malabo", timeZone: "Africa/Malabo", countryZh: "赤道几内亚" },
  { id: "asmara", labelZh: "阿斯马拉", labelEn: "Asmara", timeZone: "Africa/Asmara", countryZh: "厄立特里亚" },
  { id: "mbabane", labelZh: "姆巴巴内", labelEn: "Mbabane", timeZone: "Africa/Mbabane", countryZh: "斯威士兰" },
  { id: "libreville", labelZh: "利伯维尔", labelEn: "Libreville", timeZone: "Africa/Libreville", countryZh: "加蓬" },
  { id: "banjul", labelZh: "班珠尔", labelEn: "Banjul", timeZone: "Africa/Banjul", countryZh: "冈比亚" },
  { id: "conakry", labelZh: "科纳克里", labelEn: "Conakry", timeZone: "Africa/Conakry", countryZh: "几内亚" },
  { id: "bissau", labelZh: "比绍", labelEn: "Bissau", timeZone: "Africa/Bissau", countryZh: "几内亚比绍" },
  { id: "georgetown", labelZh: "乔治敦", labelEn: "Georgetown", timeZone: "America/Guyana", countryZh: "圭亚那" },
  { id: "portauPrince", labelZh: "太子港", labelEn: "Port-au-Prince", timeZone: "America/Port-au-Prince", countryZh: "海地" },
  { id: "tegucigalpa", labelZh: "特古西加尔巴", labelEn: "Tegucigalpa", timeZone: "America/Tegucigalpa", countryZh: "洪都拉斯" },
  { id: "tarawa", labelZh: "塔拉瓦", labelEn: "Tarawa", timeZone: "Pacific/Tarawa", countryZh: "基里巴斯" },
  { id: "pristina", labelZh: "普里什蒂纳", labelEn: "Pristina", timeZone: "Europe/Belgrade", countryZh: "科索沃" },
  { id: "maseru", labelZh: "马塞卢", labelEn: "Maseru", timeZone: "Africa/Maseru", countryZh: "莱索托" },
  { id: "monrovia", labelZh: "蒙罗维亚", labelEn: "Monrovia", timeZone: "Africa/Monrovia", countryZh: "利比里亚" },
  { id: "vaduz", labelZh: "瓦杜兹", labelEn: "Vaduz", timeZone: "Europe/Vaduz", countryZh: "列支敦士登" },
  { id: "skopje", labelZh: "斯科普里", labelEn: "Skopje", timeZone: "Europe/Skopje", countryZh: "北马其顿" },
  { id: "lilongwe", labelZh: "利隆圭", labelEn: "Lilongwe", timeZone: "Africa/Blantyre", countryZh: "马拉维" },
  { id: "male", labelZh: "马累", labelEn: "Male", timeZone: "Indian/Maldives", countryZh: "马尔代夫", aliases: ["Malé"] },
  { id: "bamako", labelZh: "巴马科", labelEn: "Bamako", timeZone: "Africa/Bamako", countryZh: "马里" },
  { id: "majuro", labelZh: "马朱罗", labelEn: "Majuro", timeZone: "Pacific/Majuro", countryZh: "马绍尔群岛" },
  { id: "nouakchott", labelZh: "努瓦克肖特", labelEn: "Nouakchott", timeZone: "Africa/Nouakchott", countryZh: "毛里塔尼亚" },
  { id: "chisinau", labelZh: "基希讷乌", labelEn: "Chisinau", timeZone: "Europe/Chisinau", countryZh: "摩尔多瓦" },
  { id: "monaco", labelZh: "摩纳哥", labelEn: "Monaco", timeZone: "Europe/Monaco", countryZh: "摩纳哥" },
  { id: "podgorica", labelZh: "波德戈里察", labelEn: "Podgorica", timeZone: "Europe/Podgorica", countryZh: "黑山" },
  { id: "managua", labelZh: "马那瓜", labelEn: "Managua", timeZone: "America/Managua", countryZh: "尼加拉瓜" },
  { id: "niamey", labelZh: "尼亚美", labelEn: "Niamey", timeZone: "Africa/Niamey", countryZh: "尼日尔" },
  { id: "ngerulmud", labelZh: "恩吉鲁穆德", labelEn: "Ngerulmud", timeZone: "Pacific/Palau", countryZh: "帕劳" },
  { id: "ramallah", labelZh: "拉姆安拉", labelEn: "Ramallah", timeZone: "Asia/Hebron", countryZh: "巴勒斯坦" },
  { id: "basseterre", labelZh: "巴斯特尔", labelEn: "Basseterre", timeZone: "America/St_Kitts", countryZh: "圣基茨和尼维斯" },
  { id: "castries", labelZh: "卡斯特里", labelEn: "Castries", timeZone: "America/St_Lucia", countryZh: "圣卢西亚" },
  { id: "kingstown", labelZh: "金斯敦", labelEn: "Kingstown", timeZone: "America/St_Vincent", countryZh: "圣文森特和格林纳丁斯" },
  { id: "apia", labelZh: "阿皮亚", labelEn: "Apia", timeZone: "Pacific/Apia", countryZh: "萨摩亚" },
  { id: "sanmarino", labelZh: "圣马力诺", labelEn: "San Marino", timeZone: "Europe/San_Marino", countryZh: "圣马力诺" },
  { id: "saotome", labelZh: "圣多美", labelEn: "Sao Tome", timeZone: "Africa/Sao_Tome", countryZh: "圣多美和普林西比" },
  { id: "victoria_sc", labelZh: "维多利亚", labelEn: "Victoria", timeZone: "Indian/Mahe", countryZh: "塞舌尔" },
  { id: "freetown", labelZh: "弗里敦", labelEn: "Freetown", timeZone: "Africa/Freetown", countryZh: "塞拉利昂" },
  { id: "honiara", labelZh: "霍尼亚拉", labelEn: "Honiara", timeZone: "Pacific/Guadalcanal", countryZh: "所罗门群岛" },
  { id: "mogadishu", labelZh: "摩加迪沙", labelEn: "Mogadishu", timeZone: "Africa/Mogadishu", countryZh: "索马里" },
  { id: "juba", labelZh: "朱巴", labelEn: "Juba", timeZone: "Africa/Juba", countryZh: "南苏丹" },
  { id: "paramaribo", labelZh: "帕拉马里博", labelEn: "Paramaribo", timeZone: "America/Paramaribo", countryZh: "苏里南" },
  { id: "bern", labelZh: "伯尔尼", labelEn: "Bern", timeZone: "Europe/Zurich", countryZh: "瑞士" },
  { id: "lome", labelZh: "洛美", labelEn: "Lome", timeZone: "Africa/Lome", countryZh: "多哥", aliases: ["Lomé"] },
  { id: "nukualofa", labelZh: "努库阿洛法", labelEn: "Nuku'alofa", timeZone: "Pacific/Tongatapu", countryZh: "汤加" },
  { id: "funafuti", labelZh: "富纳富提", labelEn: "Funafuti", timeZone: "Pacific/Funafuti", countryZh: "图瓦卢" },
  { id: "vaticancity", labelZh: "梵蒂冈", labelEn: "Vatican City", timeZone: "Europe/Rome", countryZh: "梵蒂冈" },
  { id: "sanaa", labelZh: "萨那", labelEn: "Sanaa", timeZone: "Asia/Aden", countryZh: "也门" },
];

export const MEETUP_TZ_CITY_COUNT = 375;
